GruntでS3にデプロイ出来るようにする
codeforchiba/festival-web pull request #3
Opened 2017-10-08 10:07 UTC by snakamu

grunt-aws-s3がわかりやすかったので、こちらを使用しました。
https://github.com/MathieuLoutre/grunt-aws-s3

よろしくお願いします。

2017-10-21 06:47 UTC, ymits commented on Gruntfile.js
> +  grunt.loadNpmTasks('grunt-aws-s3');
このプラグイン読み込みは必要ないですよ。自動でロードさせてます。

gruntfile.jsの10行目あたりに以下の行があると思います。

> // Load grunt tasks automatically
>   require('load-grunt-tasks')(grunt);

これで”grunt-”で始まるライブラリを自動でロードさせてます。

2017-10-25 12:42 UTC, snakamu commented on Gruntfile.js
> +  grunt.loadNpmTasks('grunt-aws-s3');
ご指摘ありがとうございます。直します。

2017-10-25 13:23 UTC, misopeso requested changes
設定値関連はコミットしたくないので、極力環境変数にしましょう。

2017-10-25 13:23 UTC, misopeso commented on Gruntfile.js
> +        region: "ap-northeast-1",
AWS に関連する設定値は、環境変数にしてもらえますか？

2017-10-25 13:23 UTC, misopeso commented on Gruntfile.js
> +          bucket: 'festival.staging.code4chiba.org',
ここも環境変数に。

2017-10-25 13:23 UTC, misopeso commented on Gruntfile.js
> +          bucket: 'festival.code4chiba.org',
ここも環境変数に。

2017-10-28 23:44 UTC, snakamu commented
@misopeso 
region,bucket名を環境変数設定に変更しました。
よろしくお願いします。

2017-10-28 23:55 UTC, misopeso commented on Gruntfile.js
> +      staging: {
Bucket 名を環境変数にするので、環境ごとのエントリっていらなくならないですか？

2017-10-29 00:01 UTC, snakamu commented on Gruntfile.js
> +      staging: {
そうですね。失礼いたしました。
直します。

2017-10-29 00:47 UTC, snakamu commented
ステージング,本番の切り替えを環境変数に変更しました。
よろしくお願いします。

2017-11-04 02:19 UTC, merged